// Generated by `python -m shortlist.server.catalogs.generate_typescript`; do not edit.
import type { RowTemplate } from "@/lib/row-templates";

import type { CollectionInput } from "@/lib/types";

export function generatedRowInputDefaults(): CollectionInput {
  return {
  "name": "",
  "build": "per_person",
  "audience": "everyone",
  "audience_user_ids": [],
  "enabled": true,
  "schedule": "30 3 * * *",
  "size": 15,
  "media": "both",
  "sort_order": 0,
  "name_template": "",
  "fallback_name": "",
  "description": "",
  "sort_title_prefix": "",
  "min_watchers": 2,
  "request_tag": "",
  "candidate_sources": [],
  "library_keys": [],
  "watched_pct": null,
  "rewatch": false,
  "rewatch_cooldown_days": 30,
  "requests_row": false,
  "requests_window_days": 90,
  "requests_tag_pattern": "",
  "unstarted_only": false,
  "refresh_days": null,
  "idle_hold_days": null,
  "recency": null,
  "recent_count": null,
  "favourite_count": null,
  "older_count": null,
  "max_seeds": null,
  "max_runtime": null,
  "min_year": null,
  "max_year": null,
  "min_rating": null,
  "cold_start": null,
  "req_min_rating": null,
  "req_min_votes": null,
  "req_min_demand": null,
  "req_min_year": null,
  "req_max_year": null,
  "req_auto_send": null,
  "req_auto_min_demand": null,
  "req_auto_min_rating": null,
  "req_max_per_row": null,
  "req_radarr_quality_profile_id": null,
  "req_radarr_root_folder": null,
  "req_sonarr_quality_profile_id": null,
  "req_sonarr_root_folder": null,
  "req_sonarr_monitor": null,
  "req_language_mode": null,
  "req_preferred_languages": null,
  "req_min_rating_other": null,
  "req_auto_user_tag": null,
  "seed_window": 1,
  "pick_order": "best",
  "placement": "both",
  "placement_friends": "both",
  "show_days": [],
  "seasons": [],
  "season_lead_days": 30,
  "season_after_days": 0,
  "pin_top": false,
  "hub_anchor": {},
  "poster": {
    "mode": "",
    "title": "",
    "subtitle": "",
    "style": ""
  },
  "ai_instructions": {
    "mode": "default",
    "text": ""
  },
  "theme_id": null,
  "theme_mode": "fixed",
  "explore_brief": "",
  "theme_days": null,
  "refresh_share": null,
  "repeat_cooldown_days": null,
  "avoid_rows": null,
  "defer_rename": false
};
}

export const GENERATED_OVER_TIME_DEFAULTS: Pick<
  CollectionInput,
  "theme_mode" | "explore_brief" | "theme_days" | "refresh_share" | "repeat_cooldown_days" | "avoid_rows"
> = {
  "theme_mode": "fixed",
  "explore_brief": "",
  "theme_days": null,
  "refresh_share": null,
  "repeat_cooldown_days": null,
  "avoid_rows": null
};

export const GENERATED_ROW_TEMPLATES: RowTemplate[] = [
  {
    "id": "picked-for-you",
    "kind": "picked",
    "emoji": "✨",
    "title": "Picked for You",
    "summary": "A little of everything they love",
    "blurb": "The everyday row. Blends someone's whole recent history into a general set of suggestions.",
    "highlights": [
      "One row each",
      "15 picks",
      "Other settings from your defaults"
    ],
    "values": {
      "name": "✨ {library_name} Picks",
      "build": "per_person",
      "size": 15
    }
  },
  {
    "id": "because-you-watched",
    "kind": "byw",
    "emoji": "🎯",
    "title": "Because you watched…",
    "summary": "One favourite leads to another",
    "blurb": "Names one recent film and fills the row with things like it. The title tells them why it's there.",
    "highlights": [
      "Films only",
      "All sources: 1 watch",
      "Follows their latest watch"
    ],
    "values": {
      "name": "🎯 Because you watched {top_seed}",
      "build": "per_person",
      "max_seeds": 1,
      "recent_count": 1,
      "media": "movie",
      "size": 20,
      "refresh_days": 1,
      "seed_window": 1
    }
  },
  {
    "id": "seen-it-already",
    "kind": "again",
    "emoji": "☕",
    "title": "Watch it again",
    "summary": "Favourites worth another look",
    "blurb": "Films and shows they've already finished, put back in front of them — a shelf of old favourites rather than new suggestions.",
    "highlights": [
      "Rewatches come first",
      "Changes slowly"
    ],
    "values": {
      "name": "☕ {library_name} you've already seen",
      "build": "per_person",
      "rewatch": true,
      "watched_pct": 1,
      "refresh_days": 11,
      "size": 15
    }
  },
  {
    "id": "your-requests",
    "kind": "requests",
    "emoji": "📬",
    "title": "Your requests",
    "summary": "What they asked for, ready to watch",
    "blurb": "What they asked for in Overseerr, once it's on Plex. Each title leaves once they've watched it.",
    "highlights": [
      "Only what they asked for",
      "Newest first",
      "Overseerr or Radarr/Sonarr tags"
    ],
    "values": {
      "name": "📬 {library_name} you asked for",
      "build": "per_person",
      "requests_row": true,
      "requests_window_days": 90,
      "size": 20
    }
  },
  {
    "id": "fresh-finds",
    "kind": "picked",
    "emoji": "🌱",
    "title": "Fresh finds",
    "summary": "Something new, every evening",
    "blurb": "Titles refresh every night, nothing they've seen. For people who want something new each evening.",
    "highlights": [
      "Refreshes nightly",
      "Nothing already watched"
    ],
    "values": {
      "name": "🌱 New {library_name} to try",
      "build": "per_person",
      "refresh_days": 1,
      "idle_hold_days": 0,
      "watched_pct": 0,
      "size": 15
    }
  },
  {
    "id": "seasonal",
    "kind": "seasonal",
    "emoji": "🗓️",
    "title": "Seasonal",
    "summary": "The right films at the right time",
    "blurb": "One shared row of the most-watched seasonal films. Follows the holidays you choose and stays hidden between seasons.",
    "highlights": [
      "Shared with everyone",
      "Needs 2 watchers",
      "Halloween, Christmas & Valentine's, or your own",
      "Shows a month before",
      "Rebuilt nightly"
    ],
    "values": {
      "name": "{season_emoji} {season} picks",
      "build": "shared",
      "min_watchers": 2,
      "media": "movie",
      "size": 15,
      "seasons": [
        "valentines",
        "halloween",
        "christmas"
      ],
      "season_lead_days": 30,
      "season_after_days": 0,
      "refresh_days": 1,
      "recency": 0
    }
  },
  {
    "id": "from-the-vault",
    "kind": "picked",
    "emoji": "🕰️",
    "title": "From the vault",
    "summary": "A shelf that takes its time",
    "blurb": "Built once and never re-picked on a schedule. A shelf that stays put apart from titles they've watched, which are replaced.",
    "highlights": [
      "Never refreshes on its own",
      "Only moves as they watch it"
    ],
    "values": {
      "name": "🕰️ {library_name} from the vault",
      "build": "per_person",
      "refresh_days": 0,
      "watched_pct": 0,
      "size": 20
    }
  },
  {
    "id": "popular-here",
    "kind": "popular",
    "emoji": "👥",
    "title": "Popular on this server",
    "summary": "What everyone’s watching",
    "blurb": "One row everybody sees, built only from titles several people have watched. Nothing personal in it.",
    "highlights": [
      "Shared with everyone",
      "Needs 3 watchers"
    ],
    "values": {
      "name": "👥 Popular {library_name} on this server",
      "build": "shared",
      "min_watchers": 3,
      "size": 20
    }
  },
  {
    "id": "movie-night",
    "kind": "picked",
    "emoji": "🍿",
    "title": "Movie night",
    "summary": "Ten films. One good evening.",
    "blurb": "Ten films picked for each person, refreshed weekly. A short list for their next movie night.",
    "highlights": [
      "Movies only",
      "10 picks",
      "Weekly"
    ],
    "values": {
      "name": "🍿 Tonight's {library_name}",
      "build": "per_person",
      "media": "movie",
      "size": 10,
      "refresh_days": 7,
      "idle_hold_days": 0
    }
  },
  {
    "id": "more-tv",
    "kind": "picked",
    "emoji": "📺",
    "title": "More TV to watch",
    "summary": "Their next series starts here",
    "blurb": "Series they have never opened — not one they're part-way through. A shelf of things to start.",
    "highlights": [
      "TV only",
      "Never started"
    ],
    "values": {
      "name": "📺 More {library_name} to watch",
      "build": "per_person",
      "media": "show",
      "unstarted_only": true,
      "watched_pct": 0,
      "size": 10
    }
  }
];

export const GENERATED_AI_TEMPLATES: RowTemplate[] = [
  {
    "id": "describe-a-row",
    "kind": "ai",
    "emoji": "🪄",
    "title": "Describe a row",
    "summary": "Say what you want. The AI builds the list.",
    "blurb": "Describe a row in your own words, like “films with a twist ending”. The AI writes the list once from your words, and Shortlist picks from it for each person every run. Set ai_paused=true when saved picks should not receive recurring AI top-ups.",
    "highlights": [
      "One row each",
      "The AI writes the list once",
      "Live like any other row"
    ],
    "values": {
      "name": "{theme_emoji} {theme}",
      "build": "per_person",
      "enabled": true,
      "size": 15,
      "recency": 0
    }
  }
];
