"""Generate the frontend row-template payload from the backend catalog."""

from __future__ import annotations

import json
from pathlib import Path

from .templates import BROWSER_ROW_INPUT_DEFAULTS, ROW_INPUT_DEFAULTS, get_template_catalog

GENERATED_PATH = Path(__file__).parents[3] / "web" / "src" / "lib" / "row-templates.generated.ts"


def render_row_templates_typescript() -> str:
    """Render the checked-in TypeScript payload.

    Returns:
        A deterministic TypeScript module preserving the existing ``RowTemplate`` contract.
    """
    templates = get_template_catalog()

    def frontend_record(template) -> dict[str, object]:
        return {
            "id": template.id,
            "kind": template.kind,
            "emoji": template.emoji,
            "title": template.title,
            "summary": template.summary,
            "blurb": template.description,
            "highlights": list(template.highlights),
            "values": template.values,
        }

    ordinary = [frontend_record(template) for template in templates if template.kind != "ai"]
    ai = [frontend_record(template) for template in templates if template.kind == "ai"]
    payload = json.dumps(ordinary, ensure_ascii=False, indent=2)
    ai_payload = json.dumps(ai, ensure_ascii=False, indent=2)
    defaults_payload = json.dumps(BROWSER_ROW_INPUT_DEFAULTS, ensure_ascii=False, indent=2)
    over_time = {
        key: ROW_INPUT_DEFAULTS[key]
        for key in ("theme_mode", "explore_brief", "theme_days", "refresh_share", "repeat_cooldown_days", "avoid_rows")
    }
    over_time_payload = json.dumps(over_time, ensure_ascii=False, indent=2)
    return (
        "// Generated by `python -m shortlist.server.catalogs.generate_typescript`; do not edit.\n"
        'import type { RowTemplate } from "@/lib/row-templates";\n\n'
        'import type { CollectionInput } from "@/lib/types";\n\n'
        "export function generatedRowInputDefaults(): CollectionInput {\n"
        f"  return {defaults_payload};\n"
        "}\n\n"
        "export const GENERATED_OVER_TIME_DEFAULTS: Pick<\n"
        "  CollectionInput,\n"
        '  "theme_mode" | "explore_brief" | "theme_days" | "refresh_share" | "repeat_cooldown_days" | "avoid_rows"\n'
        f"> = {over_time_payload};\n\n"
        f"export const GENERATED_ROW_TEMPLATES: RowTemplate[] = {payload};\n\n"
        f"export const GENERATED_AI_TEMPLATES: RowTemplate[] = {ai_payload};\n"
    )


def main() -> None:
    """Write the deterministic frontend payload to its checked-in location."""
    GENERATED_PATH.write_text(render_row_templates_typescript())


if __name__ == "__main__":
    main()
