import type { Collection } from "@/lib/types";

/** A complete row as the API returns it: every field set, so a test overrides only what it is about. */
export function fullCollection(patch: Partial<Collection> = {}): Collection {
  return {
    id: 1,
    slug: "hidden-gems",
    name: "Hidden Gems",
    last_run_id: null,
    preview_titles: [],
    build: "per_person",
    audience: "everyone",
    audience_user_ids: [],
    enabled: true,
    schedule: "30 3 * * *",
    size: 15,
    media: "both",
    sort_order: 0,
    name_template: "",
    fallback_name: "",
    description: "",
    sort_title_prefix: "",
    min_watchers: 2,
    request_tag: "",
    candidate_sources: [],
    library_keys: [],
    watched_pct: null,
    rewatch: false,
    rewatch_cooldown_days: 30,
    requests_row: false,
    requests_window_days: 90,
    requests_tag_pattern: "",
    unstarted_only: false,
    refresh_days: null,
    idle_hold_days: null,
    recency: null,
    recent_count: null,
    favourite_count: null,
    older_count: null,
    max_seeds: null,
    max_runtime: null,
    min_year: null,
    max_year: null,
    min_rating: null,
    cold_start: null,
    req_min_rating: null,
    req_min_votes: null,
    req_min_demand: null,
    req_min_year: null,
    req_max_year: null,
    req_auto_send: null,
    req_auto_min_demand: null,
    req_auto_min_rating: null,
    req_max_per_row: null,
    req_radarr_quality_profile_id: null,
    req_radarr_root_folder: null,
    req_sonarr_quality_profile_id: null,
    req_sonarr_root_folder: null,
    req_sonarr_monitor: null,
    req_language_mode: null,
    req_preferred_languages: null,
    req_min_rating_other: null,
    seed_window: 1,
    pick_order: "best",
    placement: "both",
    placement_friends: "both",
    show_days: [],
    shown_today: true,
    seasons: [],
    season_lead_days: 30,
    season_after_days: 0,
    season_status: null,
    pin_top: false,
    hub_anchor: {},
    poster: { mode: "", title: "", subtitle: "", style: "", has_image: false },
    ai_instructions: { mode: "default", text: "" },
    theme_id: null,
    theme_name: null,
    theme_emoji: null,
    ai_paused: false,
    ai_tokens: 0,
    theme_mode: "fixed",
    explore_brief: "",
    theme_days: null,
    refresh_share: null,
    repeat_cooldown_days: null,
    avoid_rows: null,
    ...patch,
  };
}

/** The handful of fields a row card reads; the rest are left off, as the card tests have always had them. */
export function cardCollection(patch: Partial<Collection> = {}): Collection {
  return {
    id: 1,
    slug: "hidden-gems",
    name: "Hidden Gems",
    last_run_id: null,
    preview_titles: [],
    build: "per_person",
    audience: "everyone",
    audience_user_ids: [],
    enabled: true,
    size: 15,
    media: "both",
    sort_order: 0,
    name_template: "",
    min_watchers: 2,
    request_tag: "",
    candidate_sources: [],
    library_keys: [],
    watched_pct: null,
    refresh_days: null,
    placement: "both",
    pin_top: false,
    hub_anchor: {},
    ...patch,
  } as Collection;
}
